### ISSUE TITLE
Custom sounds do not work in 1.11 +

### ISSUE THREAD

**Issue by Chengers** [mcRPW/rpw#110]
**What happened?**
I created a resource pack with a custom sound named `Hey.ogg`. Using the sound handling menu I successfully exported the resource pack into Minecraft with the custom sound. The custom sound plays in 1.10.2 but not in any version higher than 1.11
...

**Steps to reproduce:**
Insert custom sound. For example `Hey.ogg`.
In a game version such as 1.12.x or 1.11.x apply resource pack and do `/playsound Hey master @a` which will not play the sound. However the same thing is done in 1.10.x the sound will play.
...

**Comment by MightyPork** [comment]
This is likely related to the changes Nathan did to the resource pack
structure in that version (data packs I think it's called).

I don't follow that development and don't think I'll have time to fix it,
but if you (or someone else) sends a pull request, I'll gladly merge it.

**Comment by Chengers** [comment]
How would I go about fixing this and forwarding a pull request? Or is there someone else I need to address this issue with?

However since files (that "Nathan" changed) have already been changed will this mean that (possibly) the custom sounds will be usable in 1.13 where the data packs are implemented?

**Comment by MightyPork** [comment]
by Nathan I mean mr Dinnerbone.

I'm not sure of the details, my entire knowledge here is based on skimming over one reddit post.

The sound exporting routine is here: https://github.com/MightyPork/rpw/blob/master/src/net/mightypork/rpw/tasks/sequences/SequenceExportProject.java#L135, if all that changed is the path. I'm not sure.

and maybe here https://github.com/MightyPork/rpw/blob/master/src/net/mightypork/rpw/tasks/sequences/SequenceExportProject.java#L225

It's an IntelliJ project, if you want to try your luck.

**Comment by MCrafterzz** [comment]
Nathan hasen't done anything with data packs before 1.13 so it doesn't have anything to do with that. I don't think that it's a problem with rpw so could you try create a resourcepack and adding it manually? to see if it has anything to do with rpw.

**Comment by Chengers** [comment]
Solved: Mojang made some changes to 1.11 and so I found over the past few weeks that my issue is caused by me using UPPERCASE. As in my example "Hey Hey.ogg" is invalid and must be changed to "hey hey.ogg" and its entry changed to lowercase. If MightyPork dosen't mind adding this to the help guide for adding custom sounds.

>"NOTE: Adding custom sounds for resource packs in versions higher than 1.11 require file names and data entries to be all lowercase. For example if I added a sound called "CracklingPork.ogg" it would not work and MUST be changed to "cracklingpork.ogg"."
