### ISSUE TITLE
crash?

### ISSUE THREAD

**Issue by LorenMak** [mcRPW/rpw#120]
*******************************************

IF YOU ARE REPORTING A BROKEN DOWNLOAD LINK:

There is nothing we can do with Dropbox breaking the links.

Go download it from the releases page here on GitHub, or https://mcrpw.github.io/

*******************************************
<- Delete this notice before sending!

**What happened?**

...

**Steps to reproduce:**

...

**Crash report (if any)**

...

**Comment by AKTheKnight** [comment]
We need more information in order to actually help fix this. Fill out all the questions in your comment:

What happened?

Steps to reproduce:

Crash report (if any)

**Comment by LorenMak** [comment]
## RPW 4.3.1 CRASH REPORT ##

Please, report this issue on GitHub (use the button below).
If possible, include THIS WHOLE LOG in the report.


Alternatively, you can send this log to MightyPork.
	E-mail: ondra@ondrovo.com


### SYSTEM INFO ###


 Key               | Value 
-------------------|-------------------------------
 Runtime name      | Java(TM) SE Runtime Environment
 Java version      | 1.6.0_65
 Java vendor       | Apple Inc.
 Java path         | /Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home
 OS name           | Mac OS X
 OS arch           | x86_64
 File encoding     | Big5
 Launch dir        | /Users/shong/Downloads
 RPW version       | 4.3.1
 Library version   | UNKNOWN
 RPW path          | /Users/shong/Library/Application Support/mcRPW
 Minecraft path    | /Users/shong/Library/Application Support/minecraft


### STACK TRACE ###


```
java.lang.UnsupportedClassVersionError: com/github/rjeschke/txtmark/Decorator : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	at net.mightypork.rpw.App.init(App.java:108)
	at net.mightypork.rpw.App.start(App.java:61)
	at net.mightypork.rpw.App.main(App.java:55)

```


### FULL LOG ###


```
[ i ] Main logger initialized.
[ i ] 2017/08/29 16:10:27
[ i ] ResourcePack Workbench v.4.3.1 (#431)
[ # ] Init started...
[ - ] Checking Minecraft installation.
[ - ] Checking working directory.
[ - ] Initializing configuration manager.
[   ] Last run version: 4.3.1 (#431)
[ i ] Using library version: UNKNOWN
[!E!] Unhandled error, opening error screen.
[!E!] java.lang.UnsupportedClassVersionError: com/github/rjeschke/txtmark/Decorator : Unsupported major.minor version 51.0
[!E!] 	at java.lang.ClassLoader.defineClass1(Native Method)
[!E!] 	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
[!E!] 	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
[!E!] 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
[!E!] 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
[!E!] 	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
[!E!] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
[!E!] 	at java.security.AccessController.doPrivileged(Native Method)
[!E!] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
[!E!] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
[!E!] 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
[!E!] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
[!E!] 	at net.mightypork.rpw.App.init(App.java:108)
[!E!] 	at net.mightypork.rpw.App.start(App.java:61)
[!E!] 	at net.mightypork.rpw.App.main(App.java:55)
[!E!] 

```


~~~ END OF REPORT ~~~

**Comment by LorenMak** [comment]
this?

**Comment by LorenMak** [comment]
what should i do

**Comment by MightyPork** [comment]
Update your Java, the version you have is several years old and long
unsupported. You need Java 8.
