### ISSUE TITLE
export to special folder, pack.mcmeta version always 0?

### ISSUE THREAD

**Issue by jomyhuang** [mcRPW/rpw#122]
when use "export resource pack to ..." special folder,
pack.mcmeta version always is 0?

**Comment by MCrafterzz** [comment]
Ok I'll take a look at it. Are the other things right? Name? Description?

**Comment by jomyhuang** [comment]
I'm not sure, but
I use 1.11.2 version, show resource is incorrect when load resource pack screen.

**Comment by MCrafterzz** [comment]
New beta has been released fixing this issue
