### ISSUE TITLE
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0

### ISSUE THREAD

**Issue by MightyPork** [mcRPW/rpw#123]
this is a report by Panda Studios that i got in e-mail

### SYSTEM INFO ###

 Key               | Value 
-------------------|-------------------------------
 Runtime name      | Java(TM) SE Runtime Environment
 Java version      | 1.8.0_144
 Java vendor       | Oracle Corporation
 Java path         | C:\Program Files\Java\jre1.8.0_144
 OS name           | Windows 10
 OS arch           | amd64
 File encoding     | Cp1252
 Launch dir        | C:\Users\FlatBlob\Desktop
 RPW version       | 4.4.0
 Library version   | null
 RPW path          | C:\Users\FlatBlob\AppData\Roaming\.mcRPW
 Minecraft path    | C:\Users\FlatBlob\AppData\Roaming\.minecraft

### STACK TRACE ###

```
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
    at java.util.ArrayList.rangeCheck(Unknown Source)
    at java.util.ArrayList.get(Unknown Source)
    at net.mightypork.rpw.App.init(App.java:79)
    at net.mightypork.rpw.App.start(App.java:59)
    at net.mightypork.rpw.App.main(App.java:54)

```

### FULL LOG ###

```
[ i ] Main logger initialized.
[ i ] 2017/09/25 22:29:49
[ i ] ResourcePack Workbench v.4.4.0 (#440)
[ # ] Init started...
[!E!] Unhandled error, opening error screen.
[!E!] java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
[!E!]     at java.util.ArrayList.rangeCheck(Unknown Source)
[!E!]     at java.util.ArrayList.get(Unknown Source)
[!E!]     at net.mightypork.rpw.App.init(App.java:79)
[!E!]     at net.mightypork.rpw.App.start(App.java:59)
[!E!]     at net.mightypork.rpw.App.main(App.java:54)
[!E!] 

```

~~~ END OF REPORT ~~~

**Comment by MCrafterzz** [comment]
Please reply to his email and tell him that it's fixed in the latest beta

**Comment by MightyPork** [comment]
already done :)
