### ISSUE TITLE
crash when trying to export stitched PNG

### ISSUE THREAD

**Issue by cointrick** [mcRPW/rpw#124]
### SYSTEM INFO ###

 Key               | Value 
-------------------|-------------------------------
 Runtime name      | Java(TM) SE Runtime Environment
 Java version      | 1.8.0_101
 Java vendor       | Oracle Corporation
 Java path         | C:\Program Files (x86)\Java\jre1.8.0_101
 OS name           | Windows 10
 OS arch           | x86
 File encoding     | Cp1252
 Launch dir        | C:\Users\frankie\Desktop
 RPW version       | 4.4.0
 Library version   | 1.11.2
 RPW path          | C:\Users\frankie\AppData\Roaming\.mcRPW
 Minecraft path    | C:\Users\frankie\AppData\Roaming\.minecraft

[   ] Dialog open: Export Stitch
[!E!] Unhandled error, opening error screen.
[!E!] java.lang.OutOfMemoryError: Java heap space
[!E!] 	at java.awt.image.DataBufferByte.<init>(Unknown Source)
[!E!] 	at java.awt.image.Raster.createInterleavedRaster(Unknown Source)
[!E!] 	at java.awt.image.BufferedImage.<init>(Unknown Source)
[!E!] 	at com.pixbits.rpw.stitcher.AssetImage.cacheImage(AssetImage.java:95)
[!E!] 	at com.pixbits.rpw.stitcher.Tasks.exportPackToStitchedPng(Tasks.java:114)
[!E!] 	at com.pixbits.rpw.stitcher.DialogExportStitch$2.actionPerformed(DialogExportStitch.java:299)
[!E!] 	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
[!E!] 	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
[!E!] 	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
[!E!] 	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
[!E!] 	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
[!E!] 	at java.awt.Component.processMouseEvent(Unknown Source)
[!E!] 	at javax.swing.JComponent.processMouseEvent(Unknown Source)
[!E!] 	at java.awt.Component.processEvent(Unknown Source)
[!E!] 	at java.awt.Container.processEvent(Unknown Source)
[!E!] 	at java.awt.Component.dispatchEventImpl(Unknown Source)
[!E!] 	at java.awt.Container.dispatchEventImpl(Unknown Source)
[!E!] 	at java.awt.Component.dispatchEvent(Unknown Source)
[!E!] 	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
[!E!] 	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
[!E!] 	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
[!E!] 	at java.awt.Container.dispatchEventImpl(Unknown Source)
[!E!] 	at java.awt.Window.dispatchEventImpl(Unknown Source)
[!E!] 	at java.awt.Component.dispatchEvent(Unknown Source)
[!E!] 	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
[!E!] 	at java.awt.EventQueue.access$500(Unknown Source)
[!E!] 	at java.awt.EventQueue$3.run(Unknown Source)
[!E!] 	at java.awt.EventQueue$3.run(Unknown Source)
[!E!] 	at java.security.AccessController.doPrivileged(Native Method)
[!E!] 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
[!E!] 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
[!E!] 	at java.awt.EventQueue$4.run(Unknown Source)
[!E!] 

```

**Comment by MCrafterzz** [comment]
Do you get this everytime? For me it workes

**Comment by colin500** [comment]
It looks to be because cointricks java ran out of memory(ram) to use 
I use to get that in minecraft when i had a windows xp machine and 256MB of ram

**Comment by MCrafterzz** [comment]
The problem is that these kind of issues sometimes can be caused by memory leaks so it's hard to know if it's a problem with the program or with his computer.
