### ISSUE TITLE
4.5.0 changelog is too wide

### ISSUE THREAD

**Issue by MightyPork** [mcRPW/rpw#127]
it will go offscreen on laptops

![screenshot_20171015_100406](https://user-images.githubusercontent.com/2041118/31582899-3a55f7d4-b190-11e7-9a28-088e6faf3c50.png)

need some line-wrap support or add `<br>`'s in the markdown file

**Comment by MCrafterzz** [comment]
Add <br>? Should I do something like this: text<br>more text?

**Comment by MightyPork** [comment]
i think that could work, or figure out how to limit width of the dialog... i don't even remember what I used for this

**Comment by MCrafterzz** [comment]
I'll text it for 4.5.1

**Comment by MCrafterzz** [comment]
< br > didn't do anything :/

**Comment by MightyPork** [comment]
maybe just shorten it if that doesnt work lol idk

**Comment by MCrafterzz** [comment]
For me it doesn't go out of screen

**Comment by MCrafterzz** [comment]
It is a lot less wide now, should work on all computers
