### ISSUE TITLE
no clear indication of what MC assets version is selected for project

### ISSUE THREAD

**Issue by MightyPork** [mcRPW/rpw#128]
other than in the titlebar

![screenshot_20171015_101036](https://user-images.githubusercontent.com/2041118/31582936-713cd49c-b191-11e7-94cd-e6c5b97bdf5a.png)

it should be pre-selected in the dialog, also would be nice to show this in the sidebar i think - it's very important info

also there is some garbage from the old storage format, when you select that, it crashes (can't run without assets, aborting. ,,,) - test by putting some junk file in the storage folder

btw i think the menu item needs a better name, took me a while to figure out what it means
![screenshot_20171015_101253](https://user-images.githubusercontent.com/2041118/31582954-a757ea1c-b191-11e7-9e71-58912d02f66a.png)
maybe something like "Select target MC version"

**Comment by MCrafterzz** [comment]
Ok so:
- Preselect current version
- Change name of dialog
- And only display correct folders

Is that all?

**Comment by MightyPork** [comment]
yeah i think that'll be a good improvement

also if you can show the current version in the sidebar, that would be useful

**Comment by MCrafterzz** [comment]
Changed name to "change target Minecraft version" is that good?

**Comment by MCrafterzz** [comment]
naming fixed

**Comment by MCrafterzz** [comment]
Why in the sidebar when it's shown at the top?

**Comment by MightyPork** [comment]
just think it's better UX
the titlebar is already pretty cluttered

like eg here under the first line
![screenshot_20171015_112800](https://user-images.githubusercontent.com/2041118/31583426-ed6e7e94-b19b-11e7-9902-2009a0d2d708.png)
