### ISSUE TITLE
Opening model crash

### ISSUE THREAD

**Issue by colin500** [mcRPW/rpw#131]
**What happened?**

i opened the mine-cart model and it crashed also in the selected item preview it just says %model%

**Steps to reproduce:**

Goto a Model
   Click Edit Model

**Crash report (if any)**
https://pastebin.com/a0zfky1w

**Comment by MightyPork** [comment]
yeah that's a bug i've also seen

it seems to have fixed itself after I re-extracted minecraft assets

**Comment by colin500** [comment]
oh ok i got thank you
great job on keep this up to date :smile:

**Comment by MightyPork** [comment]
@MCrafterzz this might need some work-around, will come up again as more users update ....

**Comment by MCrafterzz** [comment]
@MightyPork I have never had that problem, what is causing it?
I think it's the node that is null but the displayednode in the sidepanel shoudn't be null so do you know what could cause this?

**Comment by MightyPork** [comment]
i don't know what exactly, but if you want to debug it, it should happen when you 

- delete .mcRPW
- run 4.3, import mc assets, make a project
- update to 4.5 without re-extracting assets

all files look blank in the sidebar preview and it crashes when you try to edit anything

**Comment by MCrafterzz** [comment]
But when you open the project in 4.5 you are forced to reextract minecraft assets
