### ISSUE TITLE
v4.5 Wants To Extract Minecraft Assets On Every Launch

### ISSUE THREAD

**Issue by Smasher277** [mcRPW/rpw#132]
Every time I launch RPW 4.5.0 or 4.5.1 it asks which Minecraft version to extract assets from. I already did this, however. When I first ran version 4.4.0 it asked which MC version to extract assets from and I chose 1.12.1, it never asked again. But with RPW version 4.5.0 and 4.5.1, it asks which MC version to extract from on first launch and it seems to go well, but If I close the app and launch it again it keeps asking which MC version to extract from.

**Comment by MightyPork** [comment]
can't reproduce, might be something messed up in the config folder?

I'd try to delete the '.mcRPW/library' folder, if that helps

**Comment by Smasher277** [comment]
I just deleted everything in the .mcRPW folder, making sure to back up my project, and launched RPW again. After extracting the assets, closing, and launching again I found my problem to be solved.
Thanks for the tip 👍
