### ISSUE TITLE
Bug/Error Report (told me to report here)

### ISSUE THREAD

**Issue by Techdude404Gaming** [mcRPW/rpw#141]
**What happened?**
I went to edit the model of the web in the models section
and it showed me an error report
...

**Steps to reproduce:**
Use 1.12.2
enter Models
scroll down to web
click web
Then click this:
![image](https://user-images.githubusercontent.com/25909830/34858925-ce5871be-f718-11e7-901e-d61801568541.png)

...

**Crash report (if any)**
https://hastebin.com/vojoyozafe.erl

...

**Comment by MCrafterzz** [comment]
Use the latest beta
