### ISSUE TITLE
Crash Report while trying to Edit model

### ISSUE THREAD

**Issue by blakfyr999** [mcRPW/rpw#144]
*******************************************

IF YOU ARE REPORTING A BROKEN DOWNLOAD LINK:

There is nothing we can do with Dropbox breaking the links.

Go download it from the releases page here on GitHub, or https://mcrpw.github.io/

*******************************************

**What happened?**

Tried to edit model

**Steps to reproduce:**

Tried to edit model for a modded item. Waystones specifically.

**Crash report (if any)**
https://pastebin.com/BiTiYYx7
...

**Comment by MCrafterzz** [comment]
Works for me
