### ISSUE TITLE
Error on trying to create a new project from an existing resourcepack

### ISSUE THREAD

**Issue by NCSGeek** [mcRPW/rpw#146]
**What happened?**
Trying to import my resourcepack that I created with this tool. it says that is was successful at the end of the console, but it says failed at the top, and it did fail, because it didnt import my resourcepack correctly.
...

**Crash report (if any)**
![screenshot_1](https://user-images.githubusercontent.com/18708328/37256690-78a58fb4-2534-11e8-8984-e016c5f205f1.png)

...

**Comment by MCrafterzz** [comment]
There's probably a problem with the pack.mcmeta file(inside the resourcepack), can you check if the file is correct?

**Comment by NCSGeek** [comment]
@MCrafterzz This is my pack.mcmeta file.

```
{"pack": {"pack_format": 3, "description": "§e§u§lPack Desc"}}
```

**Comment by Benzix123** [comment]
Can someone please please help me with my issue? Thanks!

**Comment by MCrafterzz** [comment]
Fixed in latest beta
