### ISSUE TITLE
Error editing Models

### ISSUE THREAD

**Issue by braydenanderson2014** [mcRPW/rpw#149]
*******************************************

IF YOU ARE REPORTING A BROKEN DOWNLOAD LINK:

There is nothing we can do with Dropbox breaking the links.

Go download it from the releases page here on GitHub, or https://mcrpw.github.io/

*******************************************
<- Delete this notice before sending!

**What happened?**

...

**Steps to reproduce:**

...

**Crash report (if any)**

...

**Comment by ichbineinNerd** [comment]
very useful...
maybe fill in the blanks?
also "delete this notice"
