### ISSUE TITLE
RPW NEEDS A NEW DEVELOPER!

### ISSUE THREAD

**Issue by MCrafterzz** [mcRPW/rpw#155]
I have kinda lost my intrest to continue with rpw. Combined with a lack of time I think it's time to search for someone who want's to continue this. It would be such a shame to see it die as it's a fantastic tool imo. If you are intrested comment below or send me a message on twitter (MCrafterzz). It requires java knowlegde and understanding of the rpw code.

**Comment by Floffah** [comment]
I'm not the best at java but i could give it a go: i could remake it completely in node.js/electron (what discord and visual studio code is made in) and make it work on browser and maybe a pro version?

**Comment by Floffah** [comment]
DM me on Discord: @Floffah#0001

**Comment by Floffah** [comment]
bear in mind, i would try and fix the bugs on the java version and when i finish the electron version i would stop (unless any really bad bugs appear) and update the electron version

**Comment by MCrafterzz** [comment]
Ok can't add you on Discord are you sure it's the right number?

**Comment by MCrafterzz** [comment]
Blockbench uses electron and therfore doesn't work on Mac. If that's still the case then it'll be quite a big problem. A total rewrite sounds like and good idea and I'll like to be part of the process (seeing what features are added etc)

**Comment by Floffah** [comment]
It turns out i had my privacy settings set up so only people that i share guilds with can send me a friend request. Try now (also it is definitely 0001) https://files.floffah.co.uk/uploads/438cee335abbb6d.png
