### ISSUE TITLE
Model editing: non-fatal (apparently) error

### ISSUE THREAD

**Issue by Floffah** [mcRPW/rpw#160]
**What happened?**

I was trying to edit a model and then it just went kapoof if you know what i mean

**Steps to reproduce:**

use windows 10: try and edit any default model.

**Crash report (if any)**

LOADS: https://pastebin.com/6zR5bHgh

**Comment by MCrafterzz** [comment]
I know people report this all the time like half of the issues is about this. The latest beta should fix it download that. https://mcrpw.github.io/#get-rpw
