### ISSUE TITLE
Error On Importing Resource Pack

### ISSUE THREAD

**Issue by techboy04** [mcRPW/rpw#161]
Version Used on both packs: 4.5.2

**What happened?**

Importing resourcepack failed

**Steps to reproduce:**

1. Opened RPW
2. Downloaded Resource Pack that was previously edited on a different PC with the same version
3. Imported it

**Crash report (if any)**

There is no crash report but I got this in the log:

> java.lang.StringIndexOutOfBoundsException:

 String index out of range: -44 [!E!] at java.lang.String.substring(Unknown Source) [!E!] at net.mightypork.rpw.struct.PackMcmeta.fromJson(PackMcmeta.java:38) [!E!] at net.mightypork.rpw.tasks.sequences.SequencePopulateProjectFromPack.stepMcmetaAndLanguages(SequencePopulateProjectFromPack.java:143) [!E!] at net.mightypork.rpw.tasks.sequences.SequencePopulateProjectFromPack.step(SequencePopulateProjectFromPack.java:91) [!E!] at net.mightypork.rpw.tasks.sequences.AbstractSequence.run(AbstractSequence.java:100) [!E!] at net.mightypork.rpw.tasks.sequences.AbstractSequence.run(AbstractSequence.java:71) [!E!] at net.mightypork.rpw.tasks.Tasks$18.run(Tasks.java:923) [!E!] at java.lang.Thread.run(Unknown 

> Source)

If there is a way to fix this please let me know.

**Comment by MCrafterzz** [comment]
It's fixed in the latest beta
