### ISSUE TITLE
Workspaces (+ MultiMC support)

### ISSUE THREAD

**Issue by MightyPork** [mcRPW/rpw#59]
This is a plan to make RPW less sucky and support multiple minecraft versions.
- After opening, RPW asks you to select workspace.
- A workspace has it's own loaded assets, configured target MC folder etc...
- Idea is that there will be a folder called `.rpw` in the workspace, with configuration info, next to the project folders

```
.rpw
   - config files, vanilla assets, imported packs for remixing...
MyProject
   - project stuffs
OtherProject
   - ...
```

**Why?**
- This will allow easy backups and project sharing (you can just zip the workspace)
- Will let people work on different MC versions or with different sets of mods
- The one-instance-at-a-time restriction may be lifted (it'll be one per workspace)

**Comment by MightyPork** [comment]
lol right

**Comment by MCrafterzz** [comment]
In the latest beta I've merged export and export to mc so you can now export to a chosen folder with all the options that export to mc had. When inporting you already can should location so what's left is the ability to have multiple version of assets loaded at the same time. This shouln't be to difficult to implement

**Comment by MCrafterzz** [comment]
You can now easly switch between minecraft versions
